defaults: &defaults
  adapter:  mysql
  socket:  <%=
   ['/opt/local/var/run/mysql5/mysqld.sock',
    '/opt/local/var/run/mysqld/mysqld.sock',
    '/var/run/mysqld/mysqld.sock',
    '/tmp/mysql.sock'].select { |f| File.exist? f }.first 
  %>
  <%= IO.readlines("#{RAILS_ROOT}/config/secrets.yml").map(&:chomp).join "\n  " if File.exists? "#{RAILS_ROOT}/config/secrets.yml" %>

development:
  database: brisbills_development
  <<: *defaults

test:
  database: briskbills_test
  <<: *defaults

production:
  database: brisbills_production
  <<: *defaults